export default [{
    tabname: '省份',
    data: [{
        "id": "52",
        "name": "贵州省",
        "full_name": "贵州省",
        "parent_id": "0",
        "level": 1
    }, {
        "id": "53",
        "name": "四川省",
        "full_name": "四川省",
        "parent_id": "0",
        "level": 1
    }, {
        "id": "54",
        "name": "云南省",
        "full_name": "云南省",
        "parent_id": "0",
        "level": 1
    }]
}, {
    tabname: '地市',
    data: [{
        "id": "5201",
        "name": "贵阳",
        "full_name": "贵州省,贵阳市",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5202",
        "name": "六盘水",
        "full_name": "贵州省,六盘水市",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5203",
        "name": "遵义",
        "full_name": "贵州省,遵义市",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5204",
        "name": "安顺",
        "full_name": "贵州省,安顺市",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5205",
        "name": "毕节",
        "full_name": "贵州省,毕节市",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5206",
        "name": "铜仁",
        "full_name": "贵州省,铜仁市",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5223",
        "name": "黔西南",
        "full_name": "贵州省,黔西南自治州",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5226",
        "name": "黔东南",
        "full_name": "贵州省,黔东南自治州",
        "parent_id": "52",
        "level": 2
    }, {
        "id": "5227",
        "name": "黔南",
        "full_name": "贵州省,黔南自治州",
        "parent_id": "52",
        "level": 2
    }]
}, {
    tabname: '区县',
    data: [{
        "id": "520102",
        "name": "南明区",
        "full_name": "贵州省,贵阳市,南明区",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520103",
        "name": "云岩区",
        "full_name": "贵州省,贵阳市,云岩区",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520111",
        "name": "花溪区",
        "full_name": "贵州省,贵阳市,花溪区",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520112",
        "name": "乌当区",
        "full_name": "贵州省,贵阳市,乌当区",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520113",
        "name": "白云区",
        "full_name": "贵州省,贵阳市,白云区",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520115",
        "name": "观山湖区",
        "full_name": "贵州省,贵阳市,观山湖区",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520121",
        "name": "开阳县",
        "full_name": "贵州省,贵阳市,开阳县",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520122",
        "name": "息烽县",
        "full_name": "贵州省,贵阳市,息烽县",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520123",
        "name": "修文县",
        "full_name": "贵州省,贵阳市,修文县",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520181",
        "name": "清镇市",
        "full_name": "贵州省,贵阳市,清镇市",
        "parent_id": "5201",
        "level": 3
    }, {
        "id": "520201",
        "name": "钟山区",
        "full_name": "贵州省,六盘水市,钟山区",
        "parent_id": "5202",
        "level": 3
    }, {
        "id": "520203",
        "name": "六枝特区",
        "full_name": "贵州省,六盘水市,六枝特区",
        "parent_id": "5202",
        "level": 3
    }, {
        "id": "520221",
        "name": "水城县",
        "full_name": "贵州省,六盘水市,水城县",
        "parent_id": "5202",
        "level": 3
    }, {
        "id": "520222",
        "name": "盘县",
        "full_name": "贵州省,六盘水市,盘县",
        "parent_id": "5202",
        "level": 3
    }, {
        "id": "520302",
        "name": "红花岗区",
        "full_name": "贵州省,遵义市,红花岗区",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520303",
        "name": "汇川区",
        "full_name": "贵州省,遵义市,汇川区",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520321",
        "name": "遵义县",
        "full_name": "贵州省,遵义市,遵义县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520322",
        "name": "桐梓县",
        "full_name": "贵州省,遵义市,桐梓县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520323",
        "name": "绥阳县",
        "full_name": "贵州省,遵义市,绥阳县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520324",
        "name": "正安县",
        "full_name": "贵州省,遵义市,正安县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520325",
        "name": "道真",
        "full_name": "贵州省,遵义市,道真自治县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520326",
        "name": "务川",
        "full_name": "贵州省,遵义市,务川自治县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520327",
        "name": "凤冈县",
        "full_name": "贵州省,遵义市,凤冈县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520328",
        "name": "湄潭县",
        "full_name": "贵州省,遵义市,湄潭县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520329",
        "name": "余庆县",
        "full_name": "贵州省,遵义市,余庆县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520330",
        "name": "习水县",
        "full_name": "贵州省,遵义市,习水县",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520381",
        "name": "赤水市",
        "full_name": "贵州省,遵义市,赤水市",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520382",
        "name": "仁怀市",
        "full_name": "贵州省,遵义市,仁怀市",
        "parent_id": "5203",
        "level": 3
    }, {
        "id": "520402",
        "name": "西秀区",
        "full_name": "贵州省,安顺市,西秀区",
        "parent_id": "5204",
        "level": 3
    }, {
        "id": "520421",
        "name": "平坝县",
        "full_name": "贵州省,安顺市,平坝县",
        "parent_id": "5204",
        "level": 3
    }, {
        "id": "520422",
        "name": "普定县",
        "full_name": "贵州省,安顺市,普定县",
        "parent_id": "5204",
        "level": 3
    }, {
        "id": "520423",
        "name": "镇宁",
        "full_name": "贵州省,安顺市,镇宁自治县",
        "parent_id": "5204",
        "level": 3
    }, {
        "id": "520424",
        "name": "关岭",
        "full_name": "贵州省,安顺市,关岭自治县",
        "parent_id": "5204",
        "level": 3
    }, {
        "id": "520425",
        "name": "紫云",
        "full_name": "贵州省,安顺市,紫云自治县",
        "parent_id": "5204",
        "level": 3
    }, {
        "id": "520502",
        "name": "七星关区",
        "full_name": "贵州省,毕节市,七星关区",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520521",
        "name": "大方县",
        "full_name": "贵州省,毕节市,大方县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520522",
        "name": "黔西县",
        "full_name": "贵州省,毕节市,黔西县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520523",
        "name": "金沙县",
        "full_name": "贵州省,毕节市,金沙县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520524",
        "name": "织金县",
        "full_name": "贵州省,毕节市,织金县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520525",
        "name": "纳雍县",
        "full_name": "贵州省,毕节市,纳雍县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520526",
        "name": "威宁",
        "full_name": "贵州省,毕节市,威宁自治县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520527",
        "name": "赫章县",
        "full_name": "贵州省,毕节市,赫章县",
        "parent_id": "5205",
        "level": 3
    }, {
        "id": "520602",
        "name": "碧江区",
        "full_name": "贵州省,铜仁市,碧江区",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520603",
        "name": "万山区",
        "full_name": "贵州省,铜仁市,万山区",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520621",
        "name": "江口县",
        "full_name": "贵州省,铜仁市,江口县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520622",
        "name": "玉屏",
        "full_name": "贵州省,铜仁市,玉屏自治县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520623",
        "name": "石阡县",
        "full_name": "贵州省,铜仁市,石阡县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520624",
        "name": "思南县",
        "full_name": "贵州省,铜仁市,思南县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520625",
        "name": "印江",
        "full_name": "贵州省,铜仁市,印江自治县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520626",
        "name": "德江县",
        "full_name": "贵州省,铜仁市,德江县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520627",
        "name": "沿河",
        "full_name": "贵州省,铜仁市,沿河自治县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "520628",
        "name": "松桃",
        "full_name": "贵州省,铜仁市,松桃自治县",
        "parent_id": "5206",
        "level": 3
    }, {
        "id": "522301",
        "name": "兴义市",
        "full_name": "贵州省,黔西南自治州,兴义市",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522322",
        "name": "兴仁县",
        "full_name": "贵州省,黔西南自治州,兴仁县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522323",
        "name": "普安县",
        "full_name": "贵州省,黔西南自治州,普安县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522324",
        "name": "晴隆县",
        "full_name": "贵州省,黔西南自治州,晴隆县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522325",
        "name": "贞丰县",
        "full_name": "贵州省,黔西南自治州,贞丰县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522326",
        "name": "望谟县",
        "full_name": "贵州省,黔西南自治州,望谟县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522327",
        "name": "册亨县",
        "full_name": "贵州省,黔西南自治州,册亨县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522328",
        "name": "安龙县",
        "full_name": "贵州省,黔西南自治州,安龙县",
        "parent_id": "5223",
        "level": 3
    }, {
        "id": "522601",
        "name": "凯里市",
        "full_name": "贵州省,黔东南自治州,凯里市",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522622",
        "name": "黄平县",
        "full_name": "贵州省,黔东南自治州,黄平县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522623",
        "name": "施秉县",
        "full_name": "贵州省,黔东南自治州,施秉县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522624",
        "name": "三穗县",
        "full_name": "贵州省,黔东南自治州,三穗县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522625",
        "name": "镇远县",
        "full_name": "贵州省,黔东南自治州,镇远县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522626",
        "name": "岑巩县",
        "full_name": "贵州省,黔东南自治州,岑巩县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522627",
        "name": "天柱县",
        "full_name": "贵州省,黔东南自治州,天柱县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522628",
        "name": "锦屏县",
        "full_name": "贵州省,黔东南自治州,锦屏县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522629",
        "name": "剑河县",
        "full_name": "贵州省,黔东南自治州,剑河县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522630",
        "name": "台江县",
        "full_name": "贵州省,黔东南自治州,台江县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522631",
        "name": "黎平县",
        "full_name": "贵州省,黔东南自治州,黎平县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522632",
        "name": "榕江县",
        "full_name": "贵州省,黔东南自治州,榕江县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522633",
        "name": "从江县",
        "full_name": "贵州省,黔东南自治州,从江县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522634",
        "name": "雷山县",
        "full_name": "贵州省,黔东南自治州,雷山县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522635",
        "name": "麻江县",
        "full_name": "贵州省,黔东南自治州,麻江县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522636",
        "name": "丹寨县",
        "full_name": "贵州省,黔东南自治州,丹寨县",
        "parent_id": "5226",
        "level": 3
    }, {
        "id": "522701",
        "name": "都匀市",
        "full_name": "贵州省,黔南自治州,都匀市",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522702",
        "name": "福泉市",
        "full_name": "贵州省,黔南自治州,福泉市",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522722",
        "name": "荔波县",
        "full_name": "贵州省,黔南自治州,荔波县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522723",
        "name": "贵定县",
        "full_name": "贵州省,黔南自治州,贵定县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522725",
        "name": "瓮安县",
        "full_name": "贵州省,黔南自治州,瓮安县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522726",
        "name": "独山县",
        "full_name": "贵州省,黔南自治州,独山县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522727",
        "name": "平塘县",
        "full_name": "贵州省,黔南自治州,平塘县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522728",
        "name": "罗甸县",
        "full_name": "贵州省,黔南自治州,罗甸县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522729",
        "name": "长顺县",
        "full_name": "贵州省,黔南自治州,长顺县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522730",
        "name": "龙里县",
        "full_name": "贵州省,黔南自治州,龙里县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522731",
        "name": "惠水县",
        "full_name": "贵州省,黔南自治州,惠水县",
        "parent_id": "5227",
        "level": 3
    }, {
        "id": "522732",
        "name": "三都",
        "full_name": "贵州省,黔南自治州,三都自治县",
        "parent_id": "5227",
        "level": 3
    }]
}]
